version: '3.3'
services:
    netlify-cms-oauth:
        ports:
            - '7080:80'
        restart: always
        container_name: provider
        image: 'ghcr.io/anjomro/netlify-cms-oauth-provider-python:latest'